language: node_js
node_js:
  - 10.15.1
cache: npm

install:
  - npm ci

scripts:
  - npm test
  - npm run build

deploy:
  - provider: pages
  - github_token: $GITHUB_TOKEN
  - skip-cleanup: true
  - on:
    branch: master